version: "3"
services:
  flask_test:
    build:
      context: ./flask
      dockerfile: Dockerfile
    image: cptkingfish/flask_test
    container_name: flask_test
    ports:
      - 3000:80
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: test-ecs
    #     awslogs-region: ap-southeast-1
    #     awslogs-stream-prefix: flask_test
  nextjs_test:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    image: cptkingfish/nextjs_test
    container_name: nextjs_test
    depends_on:
      - flask_test
    ports:
      - 80:3000
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: foodtrucks
    #     awslogs-region: ap-southeast-1
    #     awslogs-stream-prefix: nextjs_test
