version: "3"
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask
    environment:
      - discovery.type=single-node
    ports:
      - 80:80
  next_js:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: next_js
    restart: always
    environment:
      - DEBUG=True
    depends_on:
      - flask
    ports:
      - 3000:3000
