version: "3"
services:
  flask:
    image: cptkingfish/flask_test
    container_name: flask
    environment:
      - discovery.type=single-node
    ports:
      - 80:80
  next-js:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    environment:
      - DEBUG=True
    depends_on:
      - flask
    ports:
      - 3000:3000

